CREATE TABLE EMPLOYEE
(
	EMPLOYEE_ID VARCHAR(40) NOT NULL UNIQUE,
	EMPLOYEE_TYPE VARCHAR(10) NOT NULL,
	ACTIVE BIT NOT NULL,
	EMPLOYEE_ADDRESS TEXT NOT NULL,
	PERSON_ID int references PERSON(PERSON_ID),
	PRIMARY KEY(EMPLOYEE_ID)
);