
CREATE TABLE CIVILIAN
(
	CIVILIAN_ID varchar(20) PRIMARY KEY NOT NULL,
	CONDITION varchar(60),
	PERSON_ID int references PERSON(PERSON_ID),
	NEXT_OF_KIN_CONTACT_NUMBERS int references CIVILIAN_NEXT_OF_KIN(CONTACT_NUMBERS) 
);