CREATE TABLE EMERGENCY (
EMERGENCY_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
EMERGENCY_TYPE VARCHAR(20) NOT NULL,
EMERGENCY_LIST_ID INT NOT NULL,
EMERGENCY_LOCATION VARCHAR(50) NOT NULL,
EMERGENCY_LEVEL INT ,
EMERGENCY_EXTRA_INFO VARCHAR(50),
EMERGENCY_REFERENCE_NUM VARCHAR(50),
EMERENCY_TIME DATETIME NOT NULL,
EMERGENCY_STATUS VARCHAR(30),
EMERGENCY_REPORTER VARCHAR(20) REFERENCES CIVILIAN(CIVILIAN_ID) NOT NULL,
EMERGENCY_HANDLER VARCHAR(40) REFERENCES EMPLOYEE(EMPLOYEE_ID),
FOREIGN KEY(EMERGENCY_LIST_ID) REFERENCES EMERGENCY_LIST(EMERGENCY_LIST_ID)
);
